server:
  port: 8080
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/love_blog?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: dsznhlc
  jpa:
    hibernate:
     ddl-auto: update
     naming:
      implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

endpoints:
  enabled: false
logging:
  file: ./kunblog.log
---
spring:
  profiles: dev
  jpa:
    show-sql: true
---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/love_blog?useUnicode=true&characterEncoding=UTF-8
endpoints:
  enabled: true
---
#OSS:
#host: http://hostel-world.oss-cn-shanghai.aliyuncs.com
#accessKeyId: LTAICVi17CxDTwVT
#accessKeySecret: qvxT2MOKjes09N9pwMWMYlkClwcDwk
#bucketName: hostel-world
#endpoint: oss-cn-shanghai.aliyuncs.com
---
security:
  basic:
    enabled: false
  oauth2:
    enabled: false
